server {
    listen 80;
    server_name ssgmce.ac.in www.ssgmce.ac.in;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ssgmce.ac.in www.ssgmce.ac.in;

    client_max_body_size 300M;

    ssl_certificate /etc/ssl/certs/b122f2a0da9231f8.crt;
    ssl_certificate_key /etc/ssl/private/your_private.key;

    location / {
        proxy_pass http://localhost:5000;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_cache_bypass $http_upgrade;

        proxy_hide_header Cross-Origin-Opener-Policy;
        proxy_hide_header Cross-Origin-Resource-Policy;
        proxy_hide_header Origin-Agent-Cluster;
    }
}
